
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	private global::Gtk.Action addAction;
	private global::Gtk.Action removeAction;
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox hbox1;
	private global::Gtk.VBox vbox3;
	private global::Gtk.Label num1;
	private global::Gtk.Entry entry1;
	private global::Gtk.Fixed fixed3;
	private global::Gtk.Fixed fixed1;
	private global::Gtk.VBox vbox4;
	private global::Gtk.Label num2;
	private global::Gtk.Entry entry2;
	private global::Gtk.Fixed fixed2;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Button sum;
	private global::Gtk.HBox hbox3;
	private global::Gtk.Button rest;
	private global::Gtk.Button mult;
	private global::Gtk.Button div;
	private global::Gtk.HBox hbox4;
	private global::Gtk.HBox hbox5;
	private global::Gtk.Label label3;
	private global::Gtk.Fixed fixed5;
	private global::Gtk.Label resultado;
	private global::Gtk.Fixed fixed4;
	private global::Gtk.HBox hbox6;
	private global::Gtk.Label label4;
	private global::Gtk.Fixed fixed6;
	private global::Gtk.Label resto;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.addAction = new global::Gtk.Action ("addAction", null, null, "gtk-add");
		w1.Add (this.addAction, null);
		this.removeAction = new global::Gtk.Action ("removeAction", null, null, "gtk-remove");
		w1.Add (this.removeAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.num1 = new global::Gtk.Label ();
		this.num1.Name = "num1";
		this.num1.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 1");
		this.vbox3.Add (this.num1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.num1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.entry1 = new global::Gtk.Entry ();
		this.entry1.CanFocus = true;
		this.entry1.Name = "entry1";
		this.entry1.IsEditable = true;
		this.entry1.InvisibleChar = '•';
		this.vbox3.Add (this.entry1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.entry1]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.fixed3 = new global::Gtk.Fixed ();
		this.fixed3.Name = "fixed3";
		this.fixed3.HasWindow = false;
		this.vbox3.Add (this.fixed3);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.fixed3]));
		w4.Position = 2;
		w4.Expand = false;
		w4.Fill = false;
		this.hbox1.Add (this.vbox3);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		this.hbox1.Add (this.fixed1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.fixed1]));
		w6.Position = 1;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.num2 = new global::Gtk.Label ();
		this.num2.Name = "num2";
		this.num2.LabelProp = global::Mono.Unix.Catalog.GetString ("Numero 2");
		this.vbox4.Add (this.num2);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.num2]));
		w7.Position = 0;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.entry2 = new global::Gtk.Entry ();
		this.entry2.CanFocus = true;
		this.entry2.Name = "entry2";
		this.entry2.IsEditable = true;
		this.entry2.InvisibleChar = '•';
		this.vbox4.Add (this.entry2);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.entry2]));
		w8.Position = 1;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.fixed2 = new global::Gtk.Fixed ();
		this.fixed2.Name = "fixed2";
		this.fixed2.HasWindow = false;
		this.vbox4.Add (this.fixed2);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fixed2]));
		w9.Position = 2;
		w9.Expand = false;
		w9.Fill = false;
		this.hbox1.Add (this.vbox4);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox4]));
		w10.Position = 2;
		w10.Expand = false;
		w10.Fill = false;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w11.Position = 0;
		w11.Expand = false;
		w11.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.sum = new global::Gtk.Button ();
		this.sum.CanFocus = true;
		this.sum.Name = "sum";
		this.sum.UseUnderline = true;
		this.sum.Label = global::Mono.Unix.Catalog.GetString ("Suma");
		this.hbox2.Add (this.sum);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.sum]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.hbox3 = new global::Gtk.HBox ();
		this.hbox3.Name = "hbox3";
		this.hbox3.Spacing = 6;
		// Container child hbox3.Gtk.Box+BoxChild
		this.rest = new global::Gtk.Button ();
		this.rest.CanFocus = true;
		this.rest.Name = "rest";
		this.rest.UseUnderline = true;
		this.rest.Label = global::Mono.Unix.Catalog.GetString ("Resta");
		this.hbox3.Add (this.rest);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.rest]));
		w13.Position = 0;
		w13.Expand = false;
		w13.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.mult = new global::Gtk.Button ();
		this.mult.CanFocus = true;
		this.mult.Name = "mult";
		this.mult.UseUnderline = true;
		this.mult.Label = global::Mono.Unix.Catalog.GetString ("Multiplicacion");
		this.hbox3.Add (this.mult);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.mult]));
		w14.Position = 1;
		w14.Expand = false;
		w14.Fill = false;
		// Container child hbox3.Gtk.Box+BoxChild
		this.div = new global::Gtk.Button ();
		this.div.CanFocus = true;
		this.div.Name = "div";
		this.div.UseUnderline = true;
		this.div.Label = global::Mono.Unix.Catalog.GetString ("Division");
		this.hbox3.Add (this.div);
		global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.div]));
		w15.Position = 2;
		w15.Expand = false;
		w15.Fill = false;
		this.hbox2.Add (this.hbox3);
		global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.hbox3]));
		w16.Position = 1;
		w16.Expand = false;
		w16.Fill = false;
		this.vbox1.Add (this.hbox2);
		global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
		w17.Position = 1;
		w17.Expand = false;
		w17.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox4 = new global::Gtk.HBox ();
		this.hbox4.Name = "hbox4";
		this.hbox4.Spacing = 6;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.hbox5.Add (this.label3);
		global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.label3]));
		w18.Position = 0;
		w18.Expand = false;
		w18.Fill = false;
		// Container child hbox5.Gtk.Box+BoxChild
		this.fixed5 = new global::Gtk.Fixed ();
		this.fixed5.Name = "fixed5";
		this.fixed5.HasWindow = false;
		this.hbox5.Add (this.fixed5);
		global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.fixed5]));
		w19.Position = 1;
		// Container child hbox5.Gtk.Box+BoxChild
		this.resultado = new global::Gtk.Label ();
		this.resultado.Name = "resultado";
		this.hbox5.Add (this.resultado);
		global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.resultado]));
		w20.Position = 2;
		w20.Expand = false;
		w20.Fill = false;
		this.hbox4.Add (this.hbox5);
		global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox5]));
		w21.Position = 0;
		// Container child hbox4.Gtk.Box+BoxChild
		this.fixed4 = new global::Gtk.Fixed ();
		this.fixed4.Name = "fixed4";
		this.fixed4.HasWindow = false;
		this.hbox4.Add (this.fixed4);
		global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.fixed4]));
		w22.Position = 1;
		// Container child hbox4.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Resto");
		this.hbox6.Add (this.label4);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.label4]));
		w23.Position = 0;
		w23.Expand = false;
		w23.Fill = false;
		// Container child hbox6.Gtk.Box+BoxChild
		this.fixed6 = new global::Gtk.Fixed ();
		this.fixed6.Name = "fixed6";
		this.fixed6.HasWindow = false;
		this.hbox6.Add (this.fixed6);
		global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.fixed6]));
		w24.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.resto = new global::Gtk.Label ();
		this.resto.Name = "resto";
		this.hbox6.Add (this.resto);
		global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.resto]));
		w25.Position = 2;
		w25.Expand = false;
		w25.Fill = false;
		this.hbox4.Add (this.hbox6);
		global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.hbox6]));
		w26.Position = 2;
		this.vbox1.Add (this.hbox4);
		global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox4]));
		w27.Position = 2;
		w27.Expand = false;
		w27.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.sum.Clicked += new global::System.EventHandler (this.OnButton1Clicked);
		this.rest.Clicked += new global::System.EventHandler (this.OnRestClicked);
		this.mult.Clicked += new global::System.EventHandler (this.OnMultClicked);
		this.div.Clicked += new global::System.EventHandler (this.OnDivClicked);
	}
}
